---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: devcontainers
    directory: '.devcontainer/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
  - package-ecosystem: "bundler"
    directory: "docs/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
