# yaml-language-server: $schema=https://taskfile.dev/schema.json
---

version: '3'

vars: {}
  # GREETING: Hello, world!

tasks:
  test:
    desc: run tests
    cmds:
      - npm test
    silent: true
