---
blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://camalot.github.io/vscode-workspace-tasks/
    about: Check the Documentation for usage instructions and examples
  - name: 💬 Discussions
    url: https://github.com/camalot/vscode-workspace-tasks/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: ⭐ Visual Studio Code Marketplace
    url: https://marketplace.visualstudio.com/items?itemName=darthminos.workspace-tasks
    about: Rate and review the extension
