---
rules:
  unpinned-uses:
    config:
      policies:
        '*': any
  excessive-permissions:
    disable: false
  # secrets-outside-env:
  #   config:
  #     allow:
  #       - CODECOV_TOKEN
  #       - OPEN_VSX_TOKEN
  #       - VS_MARKETPLACE_TOKEN
