---
rules:
  unpinned-uses:
    config:
      policies:
        '*': any
  excessive-permissions:
    config:
      policies:
        '*': deny
  secrets-outside-env:
    config:
      allow:
        - CODECOV_TOKEN
