# load any
# $HOME/.devcontainer/.env.*
# $HOME/.devcontainer/*.env.*
# $HOME/.devcontainer/.env/*
# $HOME/.devcontainer/.env
# in that order, with later files taking precedence over earlier ones. This allows for flexible environment variable management, including support for multiple .env files and directories.

# if there are no matches for the globs, we need to prevent the loop from running with the literal glob pattern as the filename, so we use nullglob
setopt nullglob
for env_file in \
    "$HOME/.devcontainer"/.env.* \
    "$HOME/.devcontainer"/*.env.* \
    "$HOME/.devcontainer"/.env/* \
    "$HOME/.devcontainer/.env"; do
  echo -e "\033[0;33mSourcing $env_file\033[0m"
  [[ -r "$env_file" ]] && source "$env_file"
done

bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

setopt INTERACTIVE_COMMENTS

# Ansible managed
# Initial .zshrc generated by ansible-systems. Customize freely — re-runs will not overwrite.

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# Powerlevel10k instant prompt — keep near the top.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# PATH additions
if [[ -d "$HOME/.krew/bin" ]] && [[ ":$PATH:" != *":$HOME/.krew/bin:"* ]]; then
  export PATH="$HOME/.krew/bin:$PATH"
fi

# Powerlevel10k config
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# BEGIN ANSIBLE MANAGED — antigen
# Prevent virtualenv activation from prepending (venv) to PS1; powerlevel10k handles this.
export VIRTUAL_ENV_DISABLE_PROMPT=1
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"
mkdir -p "$ZSH_CACHE_DIR/completions" "$ZSH_CUSTOM"
source "$HOME/.antigen.zsh"
antigen use oh-my-zsh
antigen theme romkatv/powerlevel10k
# Ensure powerlevel10k is loaded
antigen bundle git
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions
# antigen bundle zsh-users/zsh-interactive-cd
# antigen bundle zsh-users/zsh-dircolors-solarized
antigen bundle direnv
antigen bundle MichaelAquilina/zsh-autoswitch-virtualenv
antigen bundle vscode
antigen bundle kubectl
antigen bundle terraform
antigen bundle azure
antigen bundle docker
antigen bundle rupa/z
antigen bundle b4b4r07/emoji-cli
antigen bundle sudo
antigen bundle aliases
antigen bundle ant
antigen bundle command-not-found
antigen bundle colorize
antigen bundle common-aliases
antigen bundle archlinux
antigen bundle dotenv
antigen bundle emoji
antigen bundle fzf
antigen bundle gh
antigen bundle history
antigen bundle npm
antigen bundle nvm
antigen bundle ruby
antigen bundle zsh-users/zsh-syntax-highlighting
autoload -Uz compinit && compinit
antigen apply
# zsh-syntax-highlighting styles
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES+=(
  [command]='fg=green,bold'
  [builtin]='fg=green,bold'
  [function]='fg=green,bold'
  [alias]='fg=green,bold'
  [reserved]='word:fg=magenta,bold'
  [commandseparator]='fg=default'
  [redirection]='fg=yellow'
  [arg0]='fg=green'
  [default]='fg=default'
  [unknown-token]='fg=red,bold'
  [path]='underline'
  [path_pathseparator]='fg=default'
  [string]='fg=cyan'
  [single-quoted-argument]='fg=cyan'
  [double-quoted-argument]='fg=cyan'
  [back-quoted-argument]='fg=magenta'
  [dollar-quoted-argument]='fg=magenta'
  [dollar-double-quoted-argument]='fg=magenta'
  [comment]='fg=black,bold'
  [globbing]='fg=blue'
  [history-expansion]='fg=blue'
)
# END ANSIBLE MANAGED — antigen
# BEGIN ANSIBLE MANAGED — zsh custom dir loader
__sources=(aliases exports functions sources)
for src in $__sources; do
  if [[ -d "$HOME/.zsh/custom/$src" ]]; then
    for file in "$HOME/.zsh/custom/$src"/*.zsh; do
      [[ -r "$file" ]] && source "$file"
    done
  fi
  if [[ -d "$HOME/.devcontainer/custom/$src" ]]; then
    for file in "$HOME/.devcontainer/custom/$src"/*.zsh; do
      [[ -r "$file" ]] && source "$file"
    done
  fi
done
# END ANSIBLE MANAGED — zsh custom dir loader
# nvm
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv >/dev/null && eval "$(pyenv init - zsh)"

# gvm (2>/dev/null suppresses a zsh/pwd compat warning that does not affect functionality)
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm" 2>/dev/null

# zoxide
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"

# thefuck
command -v thefuck >/dev/null && eval "$(thefuck --alias)"

export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;33;44m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[4;1;32m'
export LESS_TERMCAP_mr=$'\e[7m'
export LESS_TERMCAP_mh=$'\e[2m'
export LESS_TERMCAP_ZN=$'\e[74m'
export LESS_TERMCAP_ZV=$'\e[75m'
export LESS_TERMCAP_ZO=$'\e[73m'
export LESS_TERMCAP_ZW=$'\e[75m'
export MANPAGER='less'
# BEGIN ANSIBLE MANAGED — mise activation
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
elif [ -x "$HOME/.local/bin/mise" ]; then
  eval "$($HOME/.local/bin/mise activate zsh)"
fi
# END ANSIBLE MANAGED — mise activation
# BEGIN ANSIBLE MANAGED — paths
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$HOME/.local/bin:$PATH"
[[ ":$PATH:" != *":$HOME/bin:"* ]] && export PATH="$HOME/bin:$PATH"
# END ANSIBLE MANAGED — paths

if command -v pnpm >/dev/null 2>&1; then
  export PNPM_HOME="$HOME/.local/share/pnpm"
  [[ ":$PATH:" != *":$PNPM_HOME:"* ]] && export PATH="$PNPM_HOME:$PATH"
fi

if [[ -d "$HOME/.cargo/bin" ]] && [[ ":$PATH:" != *":$HOME/.cargo/bin:"* ]]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
[[ -d "$HOME/.cargo/bin" ]] && export PATH="$HOME/.cargo/bin:$PATH"
if [[ -f "$HOME/.cargo/env" ]]; then
  . "$HOME/.cargo/env"
fi
