# Ansible managed
# Initial .zshrc generated by ansible-systems. Customize freely — re-runs will not overwrite.

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# Powerlevel10k instant prompt — keep near the top.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"

fi


setopt INTERACTIVE_COMMENTS
unsetopt BEEP
bindkey '^H' backward-kill-word
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# PATH additions
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"
[[ -d "$HOME/.krew/bin" ]] && export PATH="$HOME/.krew/bin:$PATH"
[[ -d "$HOME/.cargo/bin" ]] && export PATH="$HOME/.cargo/bin:$PATH"

# Static shell completions dropped by ansible (see roles/_common/tasks/install_completions.yml).
# Must be on fpath before compinit runs, whichever init path below runs it.
[[ -d "$HOME/.zsh/completions" ]] && fpath=("$HOME/.zsh/completions" $fpath)

# fzf — point the oh-my-zsh plugin at the apt-installed location when ~/.fzf is absent
[[ ! -d "$HOME/.fzf" ]] && [[ -d "/usr/share/doc/fzf/examples" ]] && export FZF_BASE=/usr/share/doc/fzf/examples

# Powerlevel10k — load theme from the ansible-managed clone so it is available
# immediately on first login, before antigen has downloaded its own copy.
_p10k_omz="$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"
(( ${+functions[p10k]} )) || { [[ -f "$_p10k_omz" ]] && source "$_p10k_omz" }
unset _p10k_omz

# Powerlevel10k config
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# dotenv plugin: auto-source .env files without prompting (must be set before
# the plugin loads). Prevents the interactive prompt from hanging/corrupting
# non-interactive login-shell probes, e.g. VS Code's devcontainer ${localEnv:...} resolution.
export ZSH_DOTENV_PROMPT=false

# BEGIN ANSIBLE MANAGED — antigen
if [[ -z "$_ANTIGEN_INITIALIZED" ]] || ! (( ${+functions[_zsh_highlight]} )); then
  ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
  mkdir -p "$ZSH_CACHE_DIR/completions"
  source "$HOME/.antigen.zsh"
  antigen use oh-my-zsh
  antigen theme romkatv/powerlevel10k
  antigen bundle git
  antigen bundle colored-man-pages
  antigen bundle zsh-users/zsh-autosuggestions
  antigen bundle zsh-users/zsh-history-substring-search
  antigen bundle MichaelAquilina/zsh-autoswitch-virtualenv
  antigen bundle sudo
  antigen bundle vscode
  antigen bundle docker
  antigen bundle rupa/z
  antigen bundle b4b4r07/emoji-cli
  antigen bundle sudo
  antigen bundle aliases
  antigen bundle ant
  antigen bundle command-not-found
  antigen bundle colorize
  antigen bundle common-aliases
  antigen bundle dotenv
  antigen bundle emoji
  antigen bundle fzf
  antigen bundle gh
  antigen bundle history
  antigen bundle npm
  antigen bundle nvm
  antigen bundle ruby
  antigen bundle direnv
  antigen bundle azure
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen apply
  # Antigen zcache does not emit source commands for standalone theme repos
  # (only fpath/path metadata). Source p10k explicitly so the p10k function
  # and prompt are available in the current session.
  _p10k_theme="${ANTIGEN_HOME:-$HOME/.antigen}/bundles/romkatv/powerlevel10k/powerlevel10k.zsh-theme"
  [[ -f "$_p10k_theme" ]] && source "$_p10k_theme"
  unset _p10k_theme
  autoload -Uz compinit && compinit
  typeset -g _ANTIGEN_INITIALIZED=1
fi
# END ANSIBLE MANAGED — antigen
# BEGIN ANSIBLE MANAGED — zsh custom dir loader
for _zsh_custom_file in \
    "$HOME/.zsh/custom/aliases"/*.zsh(N) \
    "$HOME/.zsh/custom/exports"/*.zsh(N) \
    "$HOME/.zsh/custom/functions"/*.zsh(N) \
    "$HOME/.zsh/custom/sources"/*.zsh(N); do
  source "$_zsh_custom_file"
done
unset _zsh_custom_file
# END ANSIBLE MANAGED — zsh custom dir loader
# nvm
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv >/dev/null && eval "$(pyenv init - zsh)"

# gvm (2>/dev/null suppresses a zsh/pwd compat warning that does not affect functionality)
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm" 2>/dev/null

# zoxide
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"

# thefuck
command -v thefuck >/dev/null && eval "$(thefuck --alias 2>/dev/null)"

export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;33;44m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[4;1;32m'
export LESS_TERMCAP_mr=$'\e[7m'
export LESS_TERMCAP_mh=$'\e[2m'
export LESS_TERMCAP_ZN=$'\e[74m'
export LESS_TERMCAP_ZV=$'\e[75m'
export LESS_TERMCAP_ZO=$'\e[73m'
export LESS_TERMCAP_ZW=$'\e[75m'
export MANPAGER='less'
# BEGIN ANSIBLE MANAGED — shell environment
export VIRTUAL_ENV_DISABLE_PROMPT=1
# END ANSIBLE MANAGED — shell environment
# BEGIN ANSIBLE MANAGED — mise activation
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
elif [ -x "$HOME/.local/bin/mise" ]; then
  eval "$($HOME/.local/bin/mise activate zsh)"
fi
# END ANSIBLE MANAGED — mise activation
# BEGIN ANSIBLE MANAGED — go-task completion
if command -v task >/dev/null 2>&1; then
  eval "$(task --completion zsh)"
fi
# END ANSIBLE MANAGED — go-task completion
# BEGIN ANSIBLE MANAGED — azd
export AZURE_DEV_COLLECT_TELEMETRY=no
if command -v azd >/dev/null 2>&1; then
  source <(azd completion zsh)
fi
# END ANSIBLE MANAGED — azd
