---
name: Lint
description: Lint the codebase using Super-Linter
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}
  enable_pr_comment:
    description: 'Enable PR comment'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Prepare Super-Linter log directory
      shell: bash
      run: mkdir -p reports/super-linter

    - name: Lint Codebase
      uses: camalot/actions/smells/lint@v1
      with:
        token: ${{ inputs.github-token }}
        super_linter_env_file: .github/linters/super-linter.env
        validate_all_codebase: true
        delete_previous_comment: true
      env:
        ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: ${{ inputs.enable_pr_comment }}
