---
title: Workspace Tasks
description: A powerful Visual Studio Code extension that automatically discovers, organizes, and runs tasks from your workspace.
logo: /assets/images/logo.png
logo_svg: /assets/images/logo.svg
github_username: camalot
github_repo: vscode-workspace-tasks
github_image_docs_url: https://raw.githubusercontent.com/camalot/vscode-workspace-tasks/refs/heads/develop/res/assets/images/docs
github_images_url: https://raw.githubusercontent.com/camalot/vscode-workspace-tasks/refs/heads/develop/res/assets/images
version: 1.13.0
# Aux links (top nav)
aux_links:
  "Marketplace":
    - "https://marketplace.visualstudio.com/items?itemName=darthminos.workspace-tasks"
  "Open VSX":
    - "https://open-vsx.org/extension/darthminos/workspace-tasks"
  "GitHub":
    - "https://github.com/camalot/vscode-workspace-tasks"
