---
name: CI

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - develop

permissions: {}
env:
  ACT: ""
jobs:
  version:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    outputs:
      ver_major_minor_patch: ${{ steps.get.outputs.major_minor_patch }}
      ver_major_minor: ${{ steps.get.outputs.major_minor }}
      ver_major: ${{ steps.get.outputs.major }}
      tag: ${{ steps.get.outputs.tag_major_minor_patch }}
      tag_major: ${{ steps.get.outputs.tag_major }}
      tag_major_minor: ${{ steps.get.outputs.tag_major_minor }}
      tag_major_minor_patch: ${{ steps.get.outputs.tag_major_minor_patch }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Determine next version
        id: get
        uses: camalot/actions/version/get@v1
        with:
          default_version: v1.0.0
          fail_on_default: true
          enable_pr_comment: true
          token: ${{ github.token }}
      - run: |
          echo "next version: ${TAG}"
        env:
          TAG: ${{ steps.get.outputs.tag_major_minor_patch }}
          VERSION: ${{ steps.get.outputs.major_minor_patch }}
          TAG_MAJOR: ${{ steps.get.outputs.tag_major }}
          TAG_MAJOR_MINOR: ${{ steps.get.outputs.tag_major_minor }}
          TAG_MAJOR_MINOR_PATCH: ${{ steps.get.outputs.tag_major_minor_patch }}
          VER_MAJOR: ${{ steps.get.outputs.major }}
          VER_MAJOR_MINOR: ${{ steps.get.outputs.major_minor }}
          VER_MAJOR_MINOR_PATCH: ${{ steps.get.outputs.major_minor_patch }}

  lint:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - version
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: ./.github/workflows/lint
        with:
          github-token: ${{ github.token }}
          enable_pr_comment: ${{ github.event_name == 'pull_request' }}

  test:

    runs-on: ubuntu-latest
    environment: production
    needs:
      - version
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: ./.github/workflows/test
        with:
          github-token: ${{ github.token }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
