name: CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop
  # pull_request:
  #   branches:
  #     - develop

permissions: {}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run check

      - name: Load Super-Linter env
        run: cat .github/env/super-linter.env >> "$GITHUB_ENV"

      - name: Super-Linter
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: '${{ github.token }}'

      - name: Build
        run: npm run compile

      - name: Test
        run: npm test

      - name: Package VSIX (dry run)
        run: npm run package:vsix

      - name: VSIX Information
        run: npx vsce ls --tree
